package es.imserso.sample.monoliticapp1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AplicacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAplicacionAllPropertiesEquals(Aplicacion expected, Aplicacion actual) {
        assertAplicacionAutoGeneratedPropertiesEquals(expected, actual);
        assertAplicacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAplicacionAllUpdatablePropertiesEquals(Aplicacion expected, Aplicacion actual) {
        assertAplicacionUpdatableFieldsEquals(expected, actual);
        assertAplicacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAplicacionAutoGeneratedPropertiesEquals(Aplicacion expected, Aplicacion actual) {
        assertThat(actual)
            .as("Verify Aplicacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAplicacionUpdatableFieldsEquals(Aplicacion expected, Aplicacion actual) {
        assertThat(actual)
            .as("Verify Aplicacion relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAplicacionUpdatableRelationshipsEquals(Aplicacion expected, Aplicacion actual) {
        // empty method
    }
}
