package es.imserso.sample.monoliticapp1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EnvioMasivoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvioMasivoAllPropertiesEquals(EnvioMasivo expected, EnvioMasivo actual) {
        assertEnvioMasivoAutoGeneratedPropertiesEquals(expected, actual);
        assertEnvioMasivoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvioMasivoAllUpdatablePropertiesEquals(EnvioMasivo expected, EnvioMasivo actual) {
        assertEnvioMasivoUpdatableFieldsEquals(expected, actual);
        assertEnvioMasivoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvioMasivoAutoGeneratedPropertiesEquals(EnvioMasivo expected, EnvioMasivo actual) {
        assertThat(actual)
            .as("Verify EnvioMasivo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvioMasivoUpdatableFieldsEquals(EnvioMasivo expected, EnvioMasivo actual) {
        assertThat(actual)
            .as("Verify EnvioMasivo relevant properties")
            .satisfies(a -> assertThat(a.getIdentificador()).as("check identificador").isEqualTo(expected.getIdentificador()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getComienzo()).as("check comienzo").isEqualTo(expected.getComienzo()))
            .satisfies(a -> assertThat(a.getFin()).as("check fin").isEqualTo(expected.getFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvioMasivoUpdatableRelationshipsEquals(EnvioMasivo expected, EnvioMasivo actual) {
        assertThat(actual)
            .as("Verify EnvioMasivo relationships")
            .satisfies(a -> assertThat(a.getAplicacion()).as("check aplicacion").isEqualTo(expected.getAplicacion()))
            .satisfies(a -> assertThat(a.getOrganismoEmisor()).as("check organismoEmisor").isEqualTo(expected.getOrganismoEmisor()));
    }
}
