package es.imserso.sample.monoliticapp1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganismoEmisorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganismoEmisorAllPropertiesEquals(OrganismoEmisor expected, OrganismoEmisor actual) {
        assertOrganismoEmisorAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganismoEmisorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganismoEmisorAllUpdatablePropertiesEquals(OrganismoEmisor expected, OrganismoEmisor actual) {
        assertOrganismoEmisorUpdatableFieldsEquals(expected, actual);
        assertOrganismoEmisorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganismoEmisorAutoGeneratedPropertiesEquals(OrganismoEmisor expected, OrganismoEmisor actual) {
        assertThat(actual)
            .as("Verify OrganismoEmisor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganismoEmisorUpdatableFieldsEquals(OrganismoEmisor expected, OrganismoEmisor actual) {
        assertThat(actual)
            .as("Verify OrganismoEmisor relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganismoEmisorUpdatableRelationshipsEquals(OrganismoEmisor expected, OrganismoEmisor actual) {
        // empty method
    }
}
